version: "3.9"

services:
  app:
    build: .
    container_name: open-back
    working_dir: /app
    command: node dist/server.js
    ports:
      - "9001:9001"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
