version: "3.9"

services:
  app:
    build: .
    container_name: my-node-app
    working_dir: /app
    command: node dist/server.js
    ports:
      - "9001:9001"
    volumes:
      # Mapeia a pasta "data" do host para dentro do container
      - ./data:/app/dist/data
